server:
  port: 8040
spring:
  application:
    name: config-server
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: test
    password: test
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        native:
          search-locations: classpath:/config-repo
        git:
          uri: https://github.com/lorelib/config-repo.git
          default-label: master
          force-pull: true
  profiles:
    active: git
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    hostname: config-server
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
management:
  security:
    enabled: false
