logging:
  level:
    root: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: test
    password: test