---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  environment: dev
  datacenter: local
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8762/eureka

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  environment: dev
  datacenter: local
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka