server:
  port: 8761
eureka:
  environment: dev
  datacenter: local
  instance:
    hostname: service-discovery
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka